SET IDENTITY_INSERT [dbo].[Questions] ON
INSERT INTO [dbo].[Questions] ([Id], [Question], [Option1], [Option2], [Option3], [Option4], [CorrectOption]) VALUES (1, N'Güçlü bir parolanın özellikleri nelerdir?', N'Uzun olması', N'Uzun, rastgele ve benzersiz olması', N'Uzun ve benzersiz olması', N'Uzun ve rastgele olması', N'Uzun, rastgele ve benzersiz olması')
INSERT INTO [dbo].[Questions] ([Id], [Question], [Option1], [Option2], [Option3], [Option4], [CorrectOption]) VALUES (2, N'Birisiyle bir şifre paylaşmak istiyorsanız, en iyi seçenek nedir?', N'E-posta ile göndermek', N'Kısa mesaj ile göndermek', N'Telefonda konuşurken söylemek', N'Bunlardan hiçbiri', N'Bunlardan hiçbiri')
INSERT INTO [dbo].[Questions] ([Id], [Question], [Option1], [Option2], [Option3], [Option4], [CorrectOption]) VALUES (3, N'İş e-posta hesabınızın güvenliği ihlal edildi ve bir veri ihlali nedeniyle sızdırıldı. En iyi eylem(ler) nedir?', N'Şifrenizi hemen değiştirin', N'İş yerinizin güvenlik ekibini bilgilendirin', N'Aynı şifreyi kullandığınız tüm sitelerde şifreyi değiştirin', N'Bunların hepsi', N'Bunların hepsi')
INSERT INTO [dbo].[Questions] ([Id], [Question], [Option1], [Option2], [Option3], [Option4], [CorrectOption]) VALUES (4, N'Hangi ay Siber Güvenlik Ayı olarak kabul edilir veya kabul edilir?', N'Eylül', N'Ekim', N'Kasım', N'Aralık', N'Ekim')
INSERT INTO [dbo].[Questions] ([Id], [Question], [Option1], [Option2], [Option3], [Option4], [CorrectOption]) VALUES (1004, N'Aşağıdakilerden hangisi bir online alışveriş sitesinin güvenilir olup olmadığına karar vermede yardımcı olur?', N'Web sitesinin adresi ''https://'' ile başlar', N'Web sitesinde ''%100 güvenli'' yazan bir mühür var', N'Sitenin iyi bir üne sahip olup olmadığını görmek için biraz araştırma yapın', N'Web sitesinde diğer müşterilerin olumlu yorumlarını okuyun', N'Sitenin iyi bir üne sahip olup olmadığını görmek için biraz araştırma yapın')
INSERT INTO [dbo].[Questions] ([Id], [Question], [Option1], [Option2], [Option3], [Option4], [CorrectOption]) VALUES (2004, N'Aşağıdakilerden hangisi zayıf bir paroladır?', N'123456', N'P@ssword', N'Abcd', N'Hepsi', N'Hepsi')
INSERT INTO [dbo].[Questions] ([Id], [Question], [Option1], [Option2], [Option3], [Option4], [CorrectOption]) VALUES (2005, N'Bir şifre ne sıklıkla değiştirilmelidir?', N'Her ay ', N'Her hafta', N'Yalnızca uzlaşma kanıtı veya şüphesi olduğunda', N'Her yıl', N'Yalnızca uzlaşma kanıtı veya şüphesi olduğunda')
INSERT INTO [dbo].[Questions] ([Id], [Question], [Option1], [Option2], [Option3], [Option4], [CorrectOption]) VALUES (2006, N'Bir web sitesi açıyorsunuz ve tarayıcı çubuğunda bir kilit var. Sitenin güvenilirliğiyle ilgili düşünceniz ne yönde olur? ', N'Bunun yasal, kötü amaçlı olmayan bir site olduğundan emin olabilirim', N'Bana sitenin %100 güvenli olduğunu söylüyor', N'Bilgisayarım (tarayıcı) ile web sitesini çalıştıran sunucu arasındaki trafik güvenlidir', N'Hiçbiri', N'Bilgisayarım (tarayıcı) ile web sitesini çalıştıran sunucu arasındaki trafik güvenlidir')
INSERT INTO [dbo].[Questions] ([Id], [Question], [Option1], [Option2], [Option3], [Option4], [CorrectOption]) VALUES (2007, N'Microsoft teknik desteğinden beklenmeyen bir telefon alırsanız ne yaparsınız?', N'Talimatları takip ederim', N'Onlara şifremi veririm', N'Onları geri ararım', N'Telefonu kapatırım', N'Telefonu kapatırım')
INSERT INTO [dbo].[Questions] ([Id], [Question], [Option1], [Option2], [Option3], [Option4], [CorrectOption]) VALUES (2008, N'Bilgisayar korsanları tarafından bilgi çalmak için birbirine bağlanan ve kullanılan bilgisayar grubuna ne denir?', N'Botnet', N'Rootkit', N'DDoS', N'Bilmiyorum', N'Botnet')
SET IDENTITY_INSERT [dbo].[Questions] OFF
